version: '3'

services:
  frontend:
    build: ./frontend
    container_name: words-frontend
    command: serve -s build -l 3000
    ports:
      - "3000:3000"
    restart: unless-stopped


  api: 
    build: ./api
    container_name: words-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: words-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db

  auth_db:
    container_name: words-auth-db
    image: mongo:latest
    volumes:
      - mongodb_auth:/data/db

  api_db:
    container_name: words-api-db
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: words-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend

volumes:
  mongodb_api:
  mongodb_auth:
