version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment:
      - MODE=DEV

  api:
    command: npm run dev
    ports:
      - '3002:3002'
    volumes:
      - ./api/src:/usr/src/app/src

  auth:
    command: npm run dev
    ports:
      - '3002:3002'
    volumes:
      - ./auth/src:/usr/src/app/src

  auth_db:
    ports:
      - '27017:27017'
    volumes:
      - mongodb_auth:/data/db

  api_db:
    ports:
      - '27018:27017'
    volumes:
      - mongodb_api:/data/db

  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf

volumes:
  mongodb_auth:
  mongodb_api: