version: '3'

services:
  auth:
    build: ./
    container_name: words-auth-dev
    command: npm run dev
    restart: unless-stopped
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://auth_db:27017/auth
      - ACCESS_TOKEN_SECRET=word-access-secret-key
      - REFRESH_TOKEN_SECRET=word-refresh-secret-key
    depends_on:
      - auth_db
    ports:
      - '3002:3002'
    networks:
      - words-dev-docker-network
    volumes:
      - ./src:/usr/src/app/src

  auth_db:
    container_name: words-auth-db-dev
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_auth:/data/db
    networks:
      - words-dev-docker-network

volumes:
  mongodb_auth:

networks:
  words-dev-docker-network:
    driver: bridge
